### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[924] = 943 is not in [0, 943)

### ISSUE THREAD

**Issue by UryWu** [SSSxCCC/Recommender-System#1]
**When I run main.py in GMF or MLP or NeuMF,it ocurrs exceptions like:**
Traceback (most recent call last):
  File "F:/Projects/Recommender-System-master/Recommender_System/algorithm/GMF/main.py", line 11, in <module>
    train(model, train_data, test_data, topk_data, epochs=10, batch=512, execution='eager')
  File "F:\Projects\Recommender-System-master\Recommender_System\algorithm\train.py", line 134, in train
    train_fn(model, train_ds, test_ds, topk_data, optimizer, loss_object, epochs)
  File "F:\Projects\Recommender-System-master\Recommender_System\algorithm\train.py", line 103, in _train_eager
    model.fit(train_ds, epochs=epochs, verbose=0, validation_data=test_ds, callbacks=[MyCallback()])
  File "E:\Anaconda3-5.2.0-Windows-x86_64\envs\tensorflow2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "E:\Anaconda3-5.2.0-Windows-x86_64\envs\tensorflow2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 372, in fit
    prefix='val_')
  File "E:\Anaconda3-5.2.0-Windows-x86_64\envs\tensorflow2\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "E:\Anaconda3-5.2.0-Windows-x86_64\envs\tensorflow2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 685, in on_epoch
    self.callbacks.on_epoch_end(epoch, epoch_logs)
  File "E:\Anaconda3-5.2.0-Windows-x86_64\envs\tensorflow2\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 298, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "F:\Projects\Recommender-System-master\Recommender_System\algorithm\train.py", line 101, in on_epoch_end
    _topk(model, topk_data)
  File "F:\Projects\Recommender-System-master\Recommender_System\algorithm\train.py", line 37, in _topk
    precisions, recalls = topk_evaluate(topk_data, score_fn, ks)
  File "F:\Projects\Recommender-System-master\Recommender_System\utility\evaluation.py", line 23, in topk_evaluate
    item_score_list = list(zip(item_set, score_fn(ui)))
  File "F:\Projects\Recommender-System-master\Recommender_System\algorithm\train.py", line 36, in <lambda>
    score_fn = lambda ui: _fast_model(model, {k: tf.constant(v, dtype=tf.int32) for k, v in ui.items()}).numpy()    
six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[924] = 943 is not in [0, 943)
	 [[node model/embedding/embedding_lookup (defined at E:\Anaconda3-5.2.0-Windows-x86_64\envs\tensorflow2\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference__fast_model_4232]

Function call stack:
_fast_model

Process finished with exit code 1

**The most valuable information is:**
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[924] = 943 is not in [0, 943)
**And it occurs in lines;**
    score_fn = lambda ui: _fast_model(model, {k: tf.constant(v, dtype=tf.int32) for k, v in ui.items()}).numpy()
Can you give me some advise?

**Comment by SSSxCCC** [comment]
This is caused by a tensorflow 2.0.0 bug, which make the model gets wrong inputs. If you upgrade your tensorflow to 2.1.0rc0, the code should run without this error.
